version: '3.7'

services:
    roominus-server:
        platform: linux/x86_64
<<<<<<< HEAD
        image: asia.gcr.io/codecamp-main-project/roominus:1.34
=======
        image: asia.gcr.io/codecamp-main-project/roominus:1.33
>>>>>>> aaa767e59fc52e8bd4aa69ad1aa4d81b3c01bb2b
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./src:/Roominus/src
        env_file:
            - ./.env
        ports:
            - 3000:3000

    my-database:
        platform: linux/x86_64
        image: mysql:latest
        environment:
            MYSQL_DATABASE: 'roominus'
            MYSQL_ROOT_PASSWORD: 'root'
        ports:
            - 3306:3306

    my-redis:
        image: redis:latest
        ports:
            - 6379:6379
