version: '3.7'

services:
    roominus-server:
        platform: linux/x86_64
        image: asia.gcr.io/codecamp-main-project/roominus:1.6
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 3000:3000
