version: '3.7'

services:
    roominus-server:
        image: asia.gcr.io/codecamp-main-project/roominus:1
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 3000:3000
